=== r1eszter/QTFL19_XMLGyak/QTFL19_1018/XMLSchemaQTFL19.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Egyszerű típusok - FElépítés -->
    <xs:element name="fesztivalozas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fesztival" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="helyszin" type="xs:string"/>
                            <xs:element name="ev" type="xs:int"/>
                        </xs:sequence>
                        <xs:attribute name="fesz_id" type="fesztivalTipus"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="tulajdonos" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="adoszam" type="xs:int"/>
                            <xs:element name="alapitas" type="xs:int"/>
                            <xs:element name="bevetel" type="xs:int"/>
                        </xs:sequence>
                        <xs:attribute name="t_id" type="tulajdonosTipus"/>
                        <xs:attribute name="fesz_t" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="fellepo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="orszag" type="xs:string"/>
                            <xs:element name="dij" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="fel_id" type="fellepoTipus"/>
                        <xs:attribute name="fel_fesz" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="bar" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="ital" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="ceg" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="b_id" type="barTipus"/>
                        <xs:attribute name="fesz_b" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="alkalmazott" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="muszak" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="fizetes" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="a_id" type="alkalmazottTipus"/>
                        <xs:attribute name="b_a" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="resztvevo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="diakigazolvany" type="xs:int"/>
                            <xs:element name="lakcim">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="telepules" type="xs:string"/>
                                        <xs:element name="utca" type="xs:string"/>
                                        <xs:element name="hazszam" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="r_id" type="resztvevoTipus"/>
                        <xs:attribute name="fesz_r" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="nyelvtudas" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nyelv" type="xs:string"/>
                            <xs:element name="szint" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="ny_id" type="nyelvtudasTipus"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="kozvelemeny" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="kerdezo" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="k_id" type="kozvelemenyTipus"/>
                        <xs:attribute name="r_id" type="xs:string"/>
                        <xs:attribute name="ny_id" type="xs:string"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>


        <!-- Sajat tipusok -->
        <xs:simpleType name="fesztivalTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="f[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="tulajdonosTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="t[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="fellepoTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="e[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="barTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="b[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="alkalmazottTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="a[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="resztvevoTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="r[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="nyelvtudasTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="ny[0-9]" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="kozvelemenyTipus">
            <xs:restriction base="xs:string">
                <xs:pattern value="k[0-9]" />
            </xs:restriction>
        </xs:simpleType>


        <!-- Elsődleges Kulcsok -->
        <xs:key name="fesztival_kulcs">
            <xs:selector xpath="fesztival"/>
            <xs:field xpath="@fesz_id"/>
        </xs:key>

        <xs:key name="tulajdonos_kulcs">
            <xs:selector xpath="tulajdonos"/>
            <xs:field xpath="@t_id"/>
        </xs:key>

        <xs:key name="fellepo_kulcs">
            <xs:selector xpath="fellepo"/>
            <xs:field xpath="@t_id"/>
        </xs:key>

        <xs:key name="bar_kulcs">
            <xs:selector xpath="bar"/>
            <xs:field xpath="@b_id"/>
        </xs:key>

        <xs:key name="alkalmazott_kulcs">
            <xs:selector xpath="alkalmazott"/>
            <xs:field xpath="@a_id"/>
        </xs:key>

        <xs:key name="resztvevo_kulcs">
            <xs:selector xpath="resztvevo"/>
            <xs:field xpath="@r_id"/>
        </xs:key>

        <xs:key name="nyelvtudas_kulcs">
            <xs:selector xpath="nyelvtudas"/>
            <xs:field xpath="@ny_id"/>
        </xs:key>

        <xs:key name="kozvelemeny_kulcs">
            <xs:selector xpath="kozvelemeny"/>
            <xs:field xpath="@k_id"/>
        </xs:key>


        <!-- Idegen Kulcsok -->
        <xs:keyref refer="fesztival_kulcs" name="fesztival_tulajdonos_idegen_kulcs">
            <xs:selector xpath="tulajdonos" />
            <xs:field xpath="@fesz_t" />
        </xs:keyref>

        <xs:keyref refer="fesztival_kulcs" name="fesztival_bar_idegen_kulcs">
            <xs:selector xpath="bar" />
            <xs:field xpath="@fesz_b" />
        </xs:keyref>

        <xs:keyref refer="bar_kulcs" name="bar_alkalmazott_idegen_kulcs">
            <xs:selector xpath="alkalmazott" />
            <xs:field xpath="@b_a" />
        </xs:keyref>

        <xs:keyref refer="fesztival_kulcs" name="fesztival_resztvevo_idegen_kulcs">
            <xs:selector xpath="resztvevo" />
            <xs:field xpath="@fesz_r" />
        </xs:keyref>


        <!-- 1:1 -->
        <xs:unique name="unique_tulajdonos">
            <xs:selector xpath="tulajdonos" />
            <xs:field xpath="@fesz_t" />
        </xs:unique>

    </xs:element>
</xs:schema>

=== r1eszter/QTFL19_XMLGyak/QTFL19_1018/XMLQTFL19.xml
<?xml version="1.0" encoding="UTF-8"?>
<fesztivalozas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaQTFL19.xsd">

    <!-- Fesztivál -->
    <fesztival fesz_id="f1">
        <nev>Burning Man</nev>
        <helyszin>Black Rock Desert, Nevada</helyszin>
        <ev>2023</ev>
    </fesztival>

    <fesztival fesz_id="f2">
        <nev>Sziget Fesztivál</nev>
        <helyszin>Budapest</helyszin>
        <ev>2023</ev>
    </fesztival>


    <!-- Tulajdonos -->
    <tulajdonos t_id="t1" fesz_t="f1">
        <nev>Tóth Tamás Péter</nev>
        <adoszam>12345678-0-33</adoszam>
        <alapitas>1986</alapitas>
        <bevetel>300.000.000.000.000</bevetel>
    </tulajdonos>

    <tulajdonos t_id="t1" fesz_t="f1">
        <nev>Súkeník Erik</nev>
        <adoszam>87654321-5-06</adoszam>
        <alapitas>2012</alapitas>
        <bevetel>24.000.000</bevetel>
    </tulajdonos>


    <!-- Fellépő -->
    <fellepo fel_id="e1" fel_fesz="f1">
        <nev>Post Malone</nev>
        <orszag>USA</orszag>
        <dij>Best Rapper</dij>
    </fellepo>

    <fellepo fel_id="e2" fel_fesz="f1">
        <nev>Gorillaz</nev>
        <orszag>USA</orszag>
        <dij>Best Band</dij>
    </fellepo>

    <fellepo fel_id="e3" fel_fesz="f2">
        <nev>Azahriah</nev>
        <orszag>Magyarorszag</orszag>
        <dij>Legjobb Dalszerző</dij>
    </fellepo>


    <!-- Bár -->
    <bar b_id="b1" fesz_b="f1">
        <nev>Burning Cocktails</nev>
        <ital>Zombie</ital>
        <ital>Shirley Temple</ital>
        <ceg>Cocktail Ltd.</ceg>
    </bar>

    <bar b_id="b2" fesz_b="f2">
        <nev>Unikornis</nev>
        <ital>Mojito</ital>
        <ital>Margarita</ital>
        <ceg>Szikra Kft.</ceg>
    </bar>


    <!-- Alkalmazott -->
    <alkalmazott a_id="a1" b_a="b1">
        <nev>Nagy Máté</nev>
        <muszak>Hetfo 15:00 - Kedd 03:00</muszak>
        <muszak>Szerda 18:00 - Csutortok 02:00</muszak>
        <muszak>Szombat 15:00 - Vasarnap 03:00</muszak>
        <fizetes>5500/h</fizetes>
    </alkalmazott>

    <alkalmazott a_id="a2" b_a="b2">
        <nev>Énekes Zoltán</nev>
        <muszak>Hetfo 8:00 - Hetfo 20:00</muszak>
        <muszak>Szerda 20:00 - Csutortok 05:00</muszak>
        <muszak>Pentek 15:00 - Szombat 03:00</muszak>
        <fizetes>3500/h</fizetes>
    </alkalmazott>


    <!-- Résztvevő -->
    <resztvevo r_id="r1" fesz_r="f1">
        <nev>Rontó Eszter</nev>
        <diakigazolvany>71523648975</diakigazolvany>
        <lakcim>
            <telepules>Malyi</telepules>
            <utca>Deak Ferenc</utca>
            <hazszam>35</hazszam>
        </lakcim>
    </resztvevo>

    <resztvevo r_id="r2" fesz_r="f2">
        <nev>Kolláth Bence</nev>
        <diakigazolvany>75683249647</diakigazolvany>
        <lakcim>
            <telepules>Miskolc</telepules>
            <utca>Görgey Artúr</utca>
            <hazszam>82 3/4</hazszam>
        </lakcim>
    </resztvevo>

    <resztvevo r_id="r3" fesz_r="f2">
        <nev>Molnár Mátyás</nev>
        <diakigazolvany>79654785214</diakigazolvany>
        <lakcim>
            <telepules>Miskolc</telepules>
            <utca>Kisfaludy Károly</utca>
            <hazszam>17 9/1</hazszam>
        </lakcim>
    </resztvevo>


    <!-- Nyelvtudas -->
    <nyelvtudas ny_id="ny1">
        <nyelv>Japan</nyelv>
        <szint>alap</szint>
    </nyelvtudas>

    <nyelvtudas ny_id="ny2">
        <nyelv>Angol</nyelv>
        <szint>kozep</szint>
    </nyelvtudas>

    <nyelvtudas ny_id="ny3">
        <nyelv>Nemet</nyelv>
        <szint>kozep</szint>
    </nyelvtudas>


    <!-- Közvélemény -->
    <kozvelemeny k_id="k1" r_id="r1" ny_id="ny1">
        <kerdezo>László Andrea</kerdezo>
    </kozvelemeny>

    <kozvelemeny k_id="k1" r_id="r2" ny_id="ny2">
        <kerdezo>László Andrea</kerdezo>
    </kozvelemeny>

    <kozvelemeny k_id="k2" r_id="r3" ny_id="ny3">
        <kerdezo>Garamszegi Márton</kerdezo>
    </kozvelemeny>

</fesztivalozas>
