=== r1eszter/QTFL19_XMLGyak/XMLTaskQTFL19/XMLSchemaQTFL19.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    
    <!-- Egyszerű Elemek -->

    <!-- könyvesbolt elemek -->
    <xs:element name="nev" type="xs:string"/>
    <xs:element name="email" type="emailType"/>
    <xs:element name="telefon" type="xs:int"/>
    <xs:element name="kapacitas" type="kapType"/>

    <!-- könyv elemek -->
    <xs:element name="cim" type="xs:string"/>
    <xs:element name="mufaj" type="xs:string"/>
    <xs:element name="iro" type="xs:string"/>

    <!-- kiadó elemek  -->
    <xs:element name="alapitas" type="dateType"/>
    <xs:element name="hely" type="xs:string"/>

    <!-- vásárló elemek -->
    <xs:element name="iranyitoszam" type="iranyType"/>

    <!-- kártya elemek -->
    <xs:element name="tipus" type="xs:string"/>
    <xs:element name="akcio" type="xs:int"/>
    <xs:element name="igenyles" type="dateType"/>

    <!-- vétel kapcsolat eleme -->
    <xs:element name="vasarlas" type="dateType"/>



    <!-- Saját Típusok -->
    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="iranyType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="kapType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9].[0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dateType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([12]\d{3}.(0[1-9]|1[0-2]).(0[1-9]|[12]\d|3[01]))"/>
        </xs:restriction>
    </xs:simpleType>


    
    <!-- Felépítés -->
    <xs:element name="konyvesvasarlas">
        <xs:complexType>
            <xs:sequence>

                <!-- könyvesbolt -->
                <xs:element name="konyvesbolt" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="nev"/>
                            <xs:element name="elerhetoseg">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="email"/>
                                        <xs:element ref="telefon"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="kapacitas"/>
                        </xs:sequence>
                        <xs:attribute name="KB_ID" type="xs:string"/>
                    </xs:complexType>
                </xs:element>

                <!-- könyv -->
                <xs:element name="konyv" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="cim"/>
                            <xs:element ref="mufaj" minOccurs="1" maxOccurs="unbounded"/>
                            <xs:element ref="iro"/>
                        </xs:sequence>
                        <xs:attribute name="K_ID" type="xs:string"/>
                    </xs:complexType>
                </xs:element>

                <!-- kiadó -->
                <xs:element name="kiado" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="nev"/>
                            <xs:element ref="alapitas"/>
                            <xs:element ref="hely"/>
                        </xs:sequence>
                        <xs:attribute name="Adoszam" type="xs:int"/>
                    </xs:complexType>
                </xs:element>

                <!-- vásárló -->
                <xs:element name="vasarlo" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="nev"/>
                            <xs:element ref="iranyitoszam"/>
                            <xs:element ref="email"/>
                        </xs:sequence>
                        <xs:attribute name="V_ID" type="xs:string"/>
                    </xs:complexType>
                </xs:element>

                <!-- kártya -->
                <xs:element name="kartya" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="tipus"/>
                            <xs:element ref="akcio"/>
                            <xs:element ref="igenyles"/>
                        </xs:sequence>
                        <xs:attribute name="vonalkod" type="xs:int"/>
                    </xs:complexType>
                </xs:element>

                <!-- vétel kapcsolat -->
                <xs:element name="vetel" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="vasarlas"/>
                        </xs:sequence>
                        <xs:attribute name="KB_ID" type="xs:string"/>
                        <xs:attribute name="V_ID" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            
            </xs:sequence>
        </xs:complexType>
    



        <!--Kulcsok-->
        <xs:key name="konyvesbolt_kulcs">
            <xs:selector xpath="konyvesbolt"/>
            <xs:field xpath="@KB_ID"/>
        </xs:key>
        
        <xs:key name="konyv_kulcs">
            <xs:selector xpath="konyv"/>
            <xs:field xpath="@K_ID"/>
        </xs:key>

        <xs:key name="kiado_kulcs">
            <xs:selector xpath="kiado"/>
            <xs:field xpath="@Adoszam"/>
        </xs:key>

        <xs:key name="vasarlo_kulcs">
            <xs:selector xpath="vasarlo"/>
            <xs:field xpath="@V_ID"/>
        </xs:key>

        <xs:key name="kartya_kulcs">
            <xs:selector xpath="kartya"/>
            <xs:field xpath="@vonalkod"/>
        </xs:key>



        <!-- Idegen kulcsok -->
        <xs:keyref refer="konyvesbolt_kulcs" name="konyvesbolt_idegen_kulcs">
            <xs:selector xpath="konyv"/>
            <xs:field xpath="@FK_bolt"/>
        </xs:keyref>

        <xs:keyref refer="konyv_kulcs" name="konyv_idegen_kulcs">
            <xs:selector xpath="kiado"/>
            <xs:field xpath="@FK_konyv"/>
        </xs:keyref>

        <xs:keyref refer="konyvesbolt_kulcs" name="vetel_konyvesbolt_idegen_kulcs">
            <xs:selector xpath="vetel"/>
            <xs:field xpath="@KB_ID"/>
        </xs:keyref>

        <xs:keyref refer="vasarlo_kulcs" name="vetel_vasarlo_idegen_kulcs">
            <xs:selector xpath="vetel"/>
            <xs:field xpath="@V_ID"/>
        </xs:keyref>



        <!-- 1:1 -->
        <xs:unique name="unique_kartya">
            <xs:selector xpath="kartya"/>
            <xs:field xpath="@FK_vendeg"/>
        </xs:unique>

    </xs:element>
</xs:schema>

=== r1eszter/QTFL19_XMLGyak/XMLTaskQTFL19/XMLQTFL19.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvesvasarlas xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaQTFL19.xsd">



    <!-- Könyvesbolt -->
    <!-- Könyvesbolt "lánc" neve : LAP -->
    <konyvesbolt KB_ID="kb1">
        <nev>LAPos</nev>
        <elerhetoseg>
            <email>lapos@gmail.com</email>
            <telefon>06305984652</telefon>
        </elerhetoseg>
        <kapacitas>19.020</kapacitas>
    </konyvesbolt>

    <konyvesbolt KB_ID="kb2">
        <nev>aLAP</nev>
        <elerhetoseg>
            <email>alap@freemail.hu</email>
            <telefon>06201523495</telefon>
        </elerhetoseg>
        <kapacitas>45.000</kapacitas>
    </konyvesbolt>

    <konyvesbolt KB_ID="kb3">
        <nev>LAPoz</nev>
        <elerhetoseg>
            <email>lapoz@gmail.hu</email>
            <telefon>06708623562</telefon>
        </elerhetoseg>
        <kapacitas>20.900</kapacitas>
    </konyvesbolt>



    <!-- Könyv -->
    <konyv K_ID="k1" FK_bolt="kb3">
        <cim>Oppa és Yeobo</cim>
        <mufaj>dráma</mufaj>
        <mufaj>romantikus</mufaj>
        <mufaj>komédia</mufaj>
        <iro>Tóth Péter Tamás</iro>
    </konyv>

    <konyv K_ID="k2" FK_bolt="kb3">
        <cim>Bankrablás</cim>
        <mufaj>thriller</mufaj>
        <mufaj>krimi</mufaj>
        <mufaj>akció</mufaj>
        <iro>Szabó János</iro>
    </konyv>

    <konyv K_ID="k3" FK_bolt="kb2">
        <cim>Shuriken</cim>
        <mufaj>akció</mufaj>
        <mufaj>tragédia</mufaj>
        <mufaj>kalandregény</mufaj>
        <iro>Bogyó Eszter</iro>
    </konyv>

    <konyv K_ID="k4" FK_bolt="kb1">
        <cim>Egyetem</cim>
        <mufaj>thriller</mufaj>
        <mufaj>horror</mufaj>
        <iro>Garamszegi Márton</iro>
    </konyv>



    <!-- Kiadó -->
    <kiado Adoszam="1234567895" FK_konyv="k3">
        <nev>Pub</nev>
        <alapitas>1980.10.21</alapitas>
        <hely>California</hely>
    </kiado>

    <kiado Adoszam="1578623598" FK_konyv="k1">
        <nev>Money</nev>
        <alapitas>2005.09.13</alapitas>
        <hely>Bikinifenék</hely>
    </kiado>

    <kiado Adoszam="1452368952" FK_konyv="k4">
        <nev>OneTrickPony</nev>
        <alapitas>2010.02.30</alapitas>
        <hely>New York</hely>
    </kiado>

    <kiado Adoszam="1982332959" FK_konyv="k2">
        <nev>KiAD</nev>
        <alapitas>1996.05.19</alapitas>
        <hely>Budapest</hely>
    </kiado>



    <!-- Vásárló -->
    <vasarlo V_ID="v1">
        <nev>Súkeník Erik</nev>
        <iranyitoszam>8596</iranyitoszam>
        <email>EriKing@gmail.com</email>
    </vasarlo>

    <vasarlo V_ID="v2">
        <nev>Szabó Dávid</nev>
        <iranyitoszam>1045</iranyitoszam>
        <email>distrect@citromail.hu</email>
    </vasarlo>

    <vasarlo V_ID="v3">
        <nev>Magyar János</nev>
        <iranyitoszam>1139</iranyitoszam>
        <email>makkos98@outlook.hu</email>
    </vasarlo>

    <vasarlo V_ID="v4">
        <nev>Bogyó Márta</nev>
        <iranyitoszam>9562</iranyitoszam>
        <email>bogyo@gmail.com</email>
    </vasarlo>

    <vasarlo V_ID="v5">
        <nev>Morty Smith</nev>
        <iranyitoszam>6243</iranyitoszam>
        <email>smith@gmail.com</email>
    </vasarlo>



    <!-- Kártya -->
    <kartya vonalkod="45236874" FK_vendeg="v1">
        <tipus>Törzsvársálói</tipus>
        <akcio>15</akcio>
        <igenyles>2015.04.28</igenyles>
    </kartya>

    <kartya vonalkod="85632982" FK_vendeg="v2">
        <tipus>Törzsvársálói</tipus>
        <akcio>90</akcio>
        <igenyles>1980.09.10</igenyles>
    </kartya>

    <kartya vonalkod="65369848" FK_vendeg="v5">
        <tipus>Ajándék</tipus>
        <akcio>30</akcio>
        <igenyles>2020.12.20</igenyles>
    </kartya>

    <kartya vonalkod="53248725" FK_vendeg="v4">
        <tipus>Törzsvársálói</tipus>
        <akcio>30</akcio>
        <igenyles>1998.06.20</igenyles>
    </kartya>

    <kartya vonalkod="35986147" FK_vendeg="v3">
        <tipus>Ajándék</tipus>
        <akcio>30</akcio>
        <igenyles>2023.08.02</igenyles>
    </kartya>



    <!-- Vétel kapcsolat -->
    <vetel KB_ID="kb1" V_ID="v3">
        <vasarlas>2018.11.04</vasarlas>
    </vetel>

    <vetel KB_ID="kb2" V_ID="v1">
        <vasarlas>2022.03.15</vasarlas>
    </vetel>

    <vetel KB_ID="kb3" V_ID="v2">
        <vasarlas>2023.08.06</vasarlas>
    </vetel>

    <vetel KB_ID="kb2" V_ID="v4">
        <vasarlas>2023.04.23</vasarlas>
    </vetel>

    <vetel KB_ID="kb1" V_ID="v5">
        <vasarlas>2020.10.08</vasarlas>
    </vetel>

    <vetel KB_ID="kb3" V_ID="v4">
        <vasarlas>2021.07.10</vasarlas>
    </vetel>


</konyvesvasarlas>
